server:
  port: ${SERVER.PORT:55000}
spring:
  application:
    name: ${SPRING.APPLICATION.NAME:sms-server}
  redis:
    host: ${REDIS.HOST:150.158.130.171}
    port: ${REDIS.PORT:56379}
    password: ${REDIS.PASSWORD:xy19981123..}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB.IP:150.158.130.171}:${DB.PORT:53306}/${DB.NAME:xingchi_framework}?useSSL=false&serverTimezone=UTC
    username: root
    password: xy19981123..
  cloud:
    nacos:
      discovery:
        group: DEV_GROUP
        server-addr: localhost:58848
eureka:
  client:
    service-url:
      defaultZone: http://localhost:58090/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

logging:
  level:
    com.xingchi: debug
xingchi:
  tornado:
    logging:
      enable: true
