server:
  port: ${SERVER_PORT:55000}
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:tornado-unique-service}
  redis:
    sentinel:
      master: mymaster
      nodes: ${REDIS_SENTINEL_NODES:150.158.130.171:57001,150.158.130.171:57002,150.158.130.171:57003}
    password: ${REDIS_PASSWORD:xy19981123..}
#    host: ${REDIS_HOST:150.158.130.171}
#    port: ${REDIS_PORT:56379}
#    password: ${REDIS_PASSWORD:xy19981123..}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_DISCOVERY_URL:150.158.130.171:58848}
        ip: ${NACOS_DISCOVERY_IP:150.158.130.171}
        port: ${NACOS_DISCOVERY_PORT:55000}
#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:58082/eureka}
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    prefer-ip-address: true
#    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
#    hostname: localhost
