version: "2.2"
services:
  gogs:
    image: gogs/gogs:latest
    container_name: gogs
    ports:
      - "53000:3000"
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/docker/gogs:/data
    restart: always
    links:
      - gogs-mysql
    privileged: true

  gogs-mysql:
    image: mysql:5.7
    container_name: gogs-mysql
    ports:
      - "53307:3306"
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/docker/gogs-mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xy19981123..
    restart: always
    privileged: true
