version: '3.2'
services:
  kkfileview: #服务名称，不是容器名，只是在文件中方便观看是按个服务
    image: keking/kkfileview:v4.0.0  #依赖的镜像
    restart: always  # 代表只要docker启动， 就会自动启动这个容器  相当于-restart参数
    container_name: kkfileview  # 容器名称  相当于 --name参数
    ports:
      - 58012:8012  #映射端口，可以指定多个，用多个-来写
    environment:
      TZ: Asia/Shanghai  #指定时区
      KK_BASE_URL: http://150.158.171.130:58012
