version: '3.0'
services:
  master:
    image: redis:latest
    container_name: redis
    restart: always
    privileged: true
    command: redis-server /usr/local/redis/redis.conf
    ports:
      - 56379:6379
    volumes:
      - /var/docker/redis/data:/data
      - /var/docker/redis/conf/redis.conf:/usr/local/redis/redis.conf
