server:
  port: ${SERVER.PORT:56000}
spring:
  application:
    name: ${SPRING.APPLICATION.NAME:shortlink-server}
  redis:
    sentinel:
      master: mymaster
      nodes:
        - 150.158.130.171:57001
        - 150.158.130.171:57002
        - 150.158.130.171:57003
    password: xy19981123..
#    host: ${REDIS.HOST:150.158.130.171}
#    port: ${REDIS.PORT:56379}
#    password: ${REDIS.PASSWORD:xy19981123..}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB.IP:150.158.130.171}:${DB.PORT:53306}/${DB.NAME:xingchi_framework}?useSSL=false&serverTimezone=UTC
    username: root
    password: xy19981123..
  cloud:
    nacos:
      discovery:
        server-addr: 150.158.130.171:58848
short-link:
  domain: http://localhost:56000
  version: /v1

mybatis-plus:
  global-config:
    banner: false
